; YTPrintScreen.ini
; Konfigurace skriptu YTPrintScreen.ahk

[Profiles]
Order="YouTube,ChatGPT,QuickN,VLC"

[Targets]
Chrome="chrome.exe"
Brave="brave.exe"
VLC="vlc.exe"
;Edge="msedge.exe"
;Firefox="firefox.exe"

[Common]
DebugMode="single"
LogFile="logs\YTPrintScreen.log"

ActivationWait=300
ActivationTimeout=2000
FullscreenWait=1200
HideControlsWait=4000
ClipboardWait=300
PowerPointWait=300

HideMouseOffsetX=20
HideMouseOffsetY=20

FullscreenKey="{F11}"
AutoFullscreen=0

DefaultPipeline="Fullscreen"
CapturePipeline="FSCUT"

FSCUT_Ratio="16:9"
FSCUT_X=195
FSCUT_Y=110
FSCUT_W=1533

Output="PowerPoint"
FileFormat="PNG"

PowerPointAutoSlide=1
PowerPointPosition="Fullscreen"

[YouTube]
MatchTitle="(?i)YouTube"
FullscreenKey="f"
AutoFullscreen=1

[ChatGPT]
MatchURL="(?i)^(https?://)?(www\.)?chatgpt\.com(?:/|$)"
AutoFullscreen=1
FSCUT_X=430
FSCUT_Y=119
FSCUT_W=1220
AutoTrimTolerance=3
CapturePipeline="FSCUT,SmartTrim"

[QuickN]
MatchURL="(?i)^(https?://)?(www\.)?(quickn\.quickbreaknews\.com|tasty\.ezyfoodies\.com)(?:/|$)"
FullscreenKey="f"
AutoFullscreen=0
DefaultPipeline="SmartTrim,FSCUTFallback"
CapturePipeline="SmartTrim,FSCUTFallback"
AutoTrimTolerance=3
PowerPointAutoSlide=0
PowerPointPosition="SizeRight"
FSCUT_Ratio="2,39:1"
FSCUT_X=0
FSCUT_Y=139
FSCUT_W=1920

[Position:SizeRight]
Left=17.13
Top=3.32
MaxWidth=13.7
MaxHeight=13.8
PositionTolerance=0.2
StackGap=0.3

[VLC]
MatchTitle="(?i)VLC media player"
FullscreenKey="f"
AutoFullscreen=0

[Others]
FullscreenKey="{F11}"
AutoFullscreen=0
